sudo: false
dist: demo/dist

language: node_js
node_js:
  - 4

cache:
  yarn: true,
  directories:
    - node_modules
    
before_install:
  - yarn add codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js


script:
   - yarn build
